os: osx
osx_image: xcode11.3
language: swift
sudo: required
install:
    - wget https://swift.org/builds/swift-5.1.3-release/xcode/swift-5.1.3-RELEASE/swift-5.1.3-RELEASE-osx.pkg
    - sudo installer -pkg swift-5.1.3-RELEASE-osx.pkg -target /
    - export PATH="/Library/Developer/Toolchains/swift-5.1.3-RELEASE.xctoolchain/usr/bin:$PATH"

script:
    - swift --version
    - swift package update
    - swift build
